apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: shop-products-rollback-
spec:
  pipelineRef:
    name: pipeline-blue-green   
  podTemplate:
    securityContext:
      fsGroup: 65532 
  params:
  - name: APP
    value: products
  - name: STEP
    value: "switch-rollback"
  workspaces:
  - name: app-source
    persistentVolumeClaim:
      claimName: workspace-pvc-shop-cd-new-version