apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: shop-products-switch-
spec:
  pipelineRef:
    name: pipeline-blue-green    
  params:
  - name: APP
    value: products
  - name: STEP
    value: "switch"
  workspaces:
  - name: app-source
    persistentVolumeClaim:
      claimName: workspace-pvc-shop-cd-new-version
