apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: shop-products-scale-down-offline-
spec:
  pipelineRef:
    name: pipeline-blue-green 
  # podTemplate:
  #   securityContext:
  #     runAsNonRoot: true
  #     runAsUser: 1001 
  params:
  - name: APP
    value: products
  - name: NEW_IMAGE_TAG
    value: "v1.1.1"
  - name: STEP
    value: "scale-down-offline"
  workspaces:
  - name: app-source
    persistentVolumeClaim:
      claimName: workspace-pvc-shop-cd-new-version